### ISSUE TITLE
Script crashing

### ISSUE THREAD

**Issue by jlautner** [NicoLugil/wifiMonitor#1]
Hi,

Thank you for developing this script.  I was trying it out and it didn't seem to solve the problem.  I ran the script manually and it was getting some errors, and they occur in the places you set file mode to 'wb'.

The main show stopper is that you use it to divert the stdout of the wifi command to the null device in the `wifi_down_up()` function, but it gives and error and never succeeds.  I changed the lines to stdout=None and now it works fine:

```
def wifi_down_up():
    subprocess.call(["wifi","down"], stdout=None)   #open(os.devnull, 'wb'))
    time.sleep(5)
    subprocess.call("wifi", stdout=None)            #open(os.devnull, 'wb'))
    time.sleep(5)
```

I also noticed one other place where it uses 'wb', when you set `KEEP_ONLY_LAST_BACKUP=False`, it calls some other routine that causes an error, so for now I just kept that at `True` because I have no need of logs if the program is doing what it is supposed to do.

I had this script running for a week, and didn't realize that it was crashing, because whenever the Yun lost wifi, I had to pull the power on it to get it to restart, and the logs didn't contain the error.

Ray

**Comment by NicoLugil** [comment]
Thanks for the feedback, but there are a couple of things I don't get.

First I dont understand why the open(os.devnull, ...  doesnt work on your Yun. It seems to be the standard way of suppressing the calls output. With None it goes to the terminal (if existant). Do you know what error it gave?

Also normally when this wifi_down_up would fail, the excpetion catcher would dump that error in the SD card's log. Unless there is another exception being raised in the excpetion part, which would make the script crash...Which I assume is what happens for you?

I do not find the other place where it uses 'wb' when setting KEEP... = False?

**Comment by NicoLugil** [comment]
I uploaded a new version. This might fix your issues...

**Comment by jlautner** [comment]
Hi, thanks.  No, I don't know what error it gave as it failed before logging and then I had to restart it to get into it.  Yes the os.devnull was causing an exception on my brand new Yun out of the box upgraded to the latest firmware.. maybe it is something in the firmware.  Using None worked for me though, and using your script I have not lost a connection in about 3 weeks of solid running.
